-- MySQL Script generated by MySQL Workbench
-- 02/05/18 15:27:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema parkerenn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parkerenn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parkerenn` DEFAULT CHARACTER SET utf8 ;
USE `parkerenn` ;

-- -----------------------------------------------------
-- Table `parkerenn`.`UserRoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkerenn`.`UserRoles` ;

CREATE TABLE IF NOT EXISTS `parkerenn`.`UserRoles` (
  `id` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkerenn`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkerenn`.`Users` ;

CREATE TABLE IF NOT EXISTS `parkerenn`.`Users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `achternaam` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_role_idx` (`role` ASC),
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role`)
    REFERENCES `parkerenn`.`UserRoles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkerenn`.`TypeParking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkerenn`.`TypeParking` ;

CREATE TABLE IF NOT EXISTS `parkerenn`.`TypeParking` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parkerenn`.`Bestellingen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parkerenn`.`Bestellingen` ;

CREATE TABLE IF NOT EXISTS `parkerenn`.`Bestellingen` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL,
  `aankomsttijd` DATE NOT NULL,
  `vertrektijd` DATE NOT NULL,
  `type` INT NOT NULL,
  `kenteken` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bestelling_type_idx` (`type` ASC),
  INDEX `fk_bestelling_users_idx` (`userId` ASC),
  CONSTRAINT `fk_bestelling_type`
    FOREIGN KEY (`type`)
    REFERENCES `parkerenn`.`TypeParking` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bestelling_users`
    FOREIGN KEY (`userId`)
    REFERENCES `parkerenn`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `parkerenn`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `parkerenn`;
INSERT INTO `parkerenn`.`Users` (`id`, `email`, `achternaam`, `password`, `role`) VALUES (123456, 'henk@gmail.com', 'Berkelaar', 'dbb96cac4a275fe5c5001f195f18f8f9e2b8c123', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `parkerenn`.`TypeParking`
-- -----------------------------------------------------
START TRANSACTION;
USE `parkerenn`;
INSERT INTO `parkerenn`.`TypeParking` (`id`, `type`) VALUES (1, 'economic');
INSERT INTO `parkerenn`.`TypeParking` (`id`, `type`) VALUES (2, 'long');
INSERT INTO `parkerenn`.`TypeParking` (`id`, `type`) VALUES (3, 'valet');

COMMIT;

